CREATE DATABASE college_db;
USE college_db;

CREATE TABLE STUDENT(
  StudentID INT PRIMARY KEY,
  Name VARCHAR(20),
  Age INT,
  Dept VARCHAR(20)
);

ALTER TABLE STUDENT ADD Email VARCHAR(30);
ALTER TABLE STUDENT MODIFY Age INT NOT NULL;
ALTER TABLE STUDENT DROP COLUMN Email;

INSERT INTO STUDENT VALUES(1,'Ravi',20,'CSE');
INSERT INTO STUDENT VALUES(2,'Priya',21,'ECE');

SELECT * FROM STUDENT;

TRUNCATE TABLE STUDENT;
DROP TABLE STUDENT;
DROP DATABASE college_db;
